"""First-class competing-hypothesis investigation workflow."""

from .actions import (
    INVESTIGATION_EXPERIMENT_ACTION_KIND,
    INVESTIGATION_REASONING_ACTION_KIND,
    InvestigationExperimentResultValidator,
    InvestigationReasoningResultValidator,
    derive_investigation_action,
    investigation_batch_from_action_result,
    investigation_design_reasoning_action,
    investigation_experiment_request_from_action,
    investigation_hypothesis_reasoning_action,
    make_investigation_experiment_action,
    make_investigation_experiment_failure,
    make_investigation_experiment_result,
)
from .policy import InvestigationPolicy, make_investigation_observation_content
from .records import (
    INVESTIGATION_BATCH_DISPOSITIONS,
    INVESTIGATION_BRANCH_STATUSES,
    INVESTIGATION_DISPOSITIONS,
    INVESTIGATION_MODES,
    INVESTIGATION_RETIREMENT_REASONS,
    INVESTIGATION_STOP_REASONS,
    InvestigationBranch,
    InvestigationEvidenceBatch,
    InvestigationExperimentRequest,
    InvestigationFinding,
    InvestigationFrontier,
    InvestigationRequest,
    InvestigationResult,
    investigation_unresolved,
)
from .workflow import (
    InvestigationProgress,
    InvestigationStep,
    InvestigationUpdate,
    InvestigationWorkflow,
    investigate,
)

__all__ = [
    "INVESTIGATION_BATCH_DISPOSITIONS",
    "INVESTIGATION_BRANCH_STATUSES",
    "INVESTIGATION_DISPOSITIONS",
    "INVESTIGATION_EXPERIMENT_ACTION_KIND",
    "INVESTIGATION_REASONING_ACTION_KIND",
    "INVESTIGATION_MODES",
    "INVESTIGATION_RETIREMENT_REASONS",
    "INVESTIGATION_STOP_REASONS",
    "InvestigationBranch",
    "InvestigationEvidenceBatch",
    "InvestigationExperimentRequest",
    "InvestigationExperimentResultValidator",
    "InvestigationReasoningResultValidator",
    "InvestigationFinding",
    "InvestigationFrontier",
    "InvestigationPolicy",
    "InvestigationProgress",
    "InvestigationRequest",
    "InvestigationResult",
    "InvestigationStep",
    "InvestigationUpdate",
    "InvestigationWorkflow",
    "derive_investigation_action",
    "investigate",
    "investigation_batch_from_action_result",
    "investigation_design_reasoning_action",
    "investigation_experiment_request_from_action",
    "investigation_hypothesis_reasoning_action",
    "investigation_unresolved",
    "make_investigation_experiment_action",
    "make_investigation_experiment_failure",
    "make_investigation_experiment_result",
    "make_investigation_observation_content",
]
