"""Explicit meta-targeting and stronger governance for recursive self-improvement."""

from .actions import (
    FORWARD_SHADOW_ACTION_KIND,
    HISTORICAL_EVALUATION_ACTION_KIND,
    INDEPENDENT_REVIEW_ACTION_KIND,
    SELF_CHANGE_ACTION_KINDS,
    SelfChangeActionResultValidator,
    evaluation_command_from_action,
    evaluation_from_result,
    make_evaluation_action,
    make_evaluation_result,
    make_review_action,
    make_review_result,
    make_self_change_failure,
    review_command_from_action,
    review_from_result,
)
from .policy import SelfChangePolicy
from .records import (
    RSI_RESULT_DISPOSITIONS,
    SELF_CHANGE_CLASSES,
    SELF_CHANGE_EVALUATION_STAGES,
    SELF_CHANGE_GATE_DISPOSITIONS,
    SELF_CHANGE_GOVERNANCE_DISPOSITIONS,
    SELF_CHANGE_RISK_TIERS,
    MetaTargetDeclaration,
    RSIRequest,
    RSIResult,
    SelfChangeApproval,
    SelfChangeEvaluation,
    SelfChangeEvaluationCommand,
    SelfChangeGovernancePolicy,
    SelfChangeGovernanceResult,
    SelfChangeReview,
    SelfChangeReviewCommand,
    SelfChangeRule,
)
from .replay import (
    SelfChangeProjection,
    governance_disposition,
    governance_outcome,
    governance_projection_fields,
    next_governance_action,
    replay_governance_state,
)
from .workflow import RSIProgress, RSIUpdate, RSIWorkflow, recurse, rsi_outcome

__all__ = [
    "FORWARD_SHADOW_ACTION_KIND",
    "HISTORICAL_EVALUATION_ACTION_KIND",
    "INDEPENDENT_REVIEW_ACTION_KIND",
    "MetaTargetDeclaration",
    "RSIProgress",
    "RSIRequest",
    "RSIResult",
    "RSIUpdate",
    "RSIWorkflow",
    "RSI_RESULT_DISPOSITIONS",
    "SELF_CHANGE_ACTION_KINDS",
    "SELF_CHANGE_CLASSES",
    "SELF_CHANGE_EVALUATION_STAGES",
    "SELF_CHANGE_GATE_DISPOSITIONS",
    "SELF_CHANGE_GOVERNANCE_DISPOSITIONS",
    "SELF_CHANGE_RISK_TIERS",
    "SelfChangeActionResultValidator",
    "SelfChangeApproval",
    "SelfChangeEvaluation",
    "SelfChangeEvaluationCommand",
    "SelfChangeGovernancePolicy",
    "SelfChangeGovernanceResult",
    "SelfChangePolicy",
    "SelfChangeProjection",
    "SelfChangeReview",
    "SelfChangeReviewCommand",
    "SelfChangeRule",
    "evaluation_command_from_action",
    "evaluation_from_result",
    "governance_disposition",
    "governance_outcome",
    "governance_projection_fields",
    "make_evaluation_action",
    "make_evaluation_result",
    "make_review_action",
    "make_review_result",
    "make_self_change_failure",
    "next_governance_action",
    "recurse",
    "rsi_outcome",
    "replay_governance_state",
    "review_command_from_action",
    "review_from_result",
]
